### ISSUE TITLE
"The Tab is inactive" message appears when the browser is minimized, the selected tab is changed, or VS Code is full screen

### ISSUE THREAD

**Issue by thevarunraja** [microsoft/vscode-edge-devtools#74]
IDK whether I am using this tool correctly or not. I am seeing the below

<img width="1680" alt="Screen Shot 2019-07-15 at 12 34 05 PM" src="https://user-images.githubusercontent.com/17805098/61232840-37865d00-a6fd-11e9-844f-f041041b1896.png">

**Comment by jalissia** [comment]
This is a limitation of the screencasting API that we are using. Right now you need to have the Edge tab that you are connected to, selected as the current tab in the browser. You also need to have the browser itself not minimized.

I'll update the title to reflect this, but keep it open in case we can find a better solution at some point.

**Comment by thevarunraja** [comment]
@jalissia Thanks for the explanation. This happens for me when I use VSCode in Zen Mode. It works like a charm in Normal mode.

**Comment by jalissia** [comment]
Interesting, I don't think I've ever tried [Zen Mode](https://code.visualstudio.com/updates/v1_8#_zen-mode). Are you on Windows or Mac? 
If I enter zen mode after attaching the elements tool (without moving the browser/tab at all) it seems to stay active for me (on Windows 10). 

Certainly something for us to look into though as I know the API has limitations.

**Comment by thevarunraja** [comment]
I am on Mac.

**Comment by vidorteg** [comment]
I can repro @thevarunraja findings. Zen mode (simplified explanation) puts vscode in fullscreen mode. In the latest mac osx versions full screen creates a "new desktop" which remove focus from the other window(s). To test this I moved vs code to "virtual dekstop 1"  (without zen mode) and Edge browser to a "virtual desktop 2" and could observe the same behavior. In short:

**Repro steps (1):**
* Open VScode with vscode-edge-devtools extension (on mac)
* Open a new window and attach to it using vscode-edge-devtools extension
* Tun Zen mode on (Ctrl-K + Z)

**Repro Steps (2):**
* Open VScode with vscode-edge-devtools extension (on mac)
* Open a new window and attach to it using vscode-edge-devtools extension
* Move vscode to a different virtual desktop

**Expected:**
Screencast should work

**Observed:**
tab is inactive appears on screen cast

Note: On Windows 10 Repro steps 2 work as expected.

**Comment by Borongaj** [comment]
MAC user here.

"The Tab is inactive" message appears when VSCode completely covers the Edge window or when they are on different screens.

The message disappear when :

- VSCode and Edge are not in full screen mode
- VSCode and Edge are on the same virtual screen
- VSCode's window is smaller than the Edge's one

**Comment by erdraud** [comment]
I encountered this while using a Windows computer with the Edge window minified. Maximizing it made it work normally.
![image](https://user-images.githubusercontent.com/53534032/62398393-79046e00-b52d-11e9-959a-199ee59743cd.png)

**Comment by codepo8** [comment]
Verified on Mac. It is enough to have the browser window one pixel bigger than the vs code one, but this is annoying. This could be a battery saving thing on Mac.

**Comment by mhamri** [comment]
having the same issue, found out that the only way to change the screen is to use alt+tab or other method rather than minimize.

**Comment by codepo8** [comment]
This could be fixed by using the headless version, let's verify that.

**Comment by mliao95** [comment]
Verified that this issue does not repro in the headless version.

**Comment by codepo8** [comment]
This is fixed.

**Comment by ffMathy** [comment]
This still happens for me on Windows. Latest Windows Update, latest VS Code, latest Edge.

Strangely, it happens even if I just ALT+Tab away from the window into VS Code.

**Comment by sagarpabba** [comment]
This is still observed with the latest version of chrome on Windows & Mac OS.
Can anyone share the resolution for mitigating this?
Thanks in advance.

**Note:** Usecase at my end is launch the browser in debug mode and interacting with it using the dev tools capability [Selenium WebDriver + debuggerAddress].

**Comment by GuttormAndreas** [comment]
Locate Chrome on your computer
Windows Button =>Chrome
Right Click and Open in Windows Explorer
Right clock on the file
Properties
Compatibility
Settings
Run this program as an administrator

Now, in Visual Studio (probably similar in VS Code), add another browser to the VS Browser list (via Browse with)
The full path
 - Program: C:\Program Files\Google\Chrome\Application\chrome.exe
 - Arguments: --remote-debugging-port=9222 --user-data-dir="%LOCALAPPDATA%\Temp\blazor-chrome-debug"
 Any name will do
 - Friendly Name: Chrome debugging 

Set this as default
Run the application

In both the browser window and the developer window, it will appear as if the application is inactive (the tab is inactive)
But. In the browser window, try to click on the menu items ! (set some breakpoints in the developer windows under Sources=>File... first). And voila !

**Comment by exo0** [comment]
A small update from my side is that when I opened this page without https (just simple HTTP), then I started getting the debugger options and the file started to be available how it should be 

Anyway, from VSCode or VS2022 it's still don't working (I'm running VSCode and VS2022 as an administrator), additionally I changed the browser properties inside VS2022 during the start to meet the same criteria that I'm using by clicking WIN + R 

![image](https://user-images.githubusercontent.com/36488878/222513191-f722cc5c-85a7-49ec-8801-9e70af74fd79.png)

**Comment by khaschuluu** [comment]
When chrome launched new headless mode (with --headless=new), this problem appears. This problem solved by launch chrome with --headless=old. For example in puppeteer.js, launch with option headless: true. Hope this help.

**Comment by o0101** [comment]
Confirmed we do not see this on `--headless` (legacy) but only on `--headless=new`. I'm going to look for some browser flags to fix this, or a way to use DevTools protocol.

For a live demo of this happening on a real headless (new) browser, check out:

https://puter.com/app/cloudtabs-browserbox

**Comment by mistcat** [comment]
I'm having this issue too, pretty much everytime I try and use this with a nextjs project.  It's super annoying!  All i have to do is open up the connected devtools, open the browser view from that, and then after a little messing around I get the "tab is inactive" overlay and there doesn't seem to be anyway to make it active ever again.  Super annoying.  On Mac with latest vs code & extension version.

**Comment by Dozorengel** [comment]
@mistcat I have the same issue on Mac, whenever I press shift focusing on the browser view inside vscode this message appears and we are done here
