### ISSUE TITLE
Microsoft Edge Tools server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by lukkea** [microsoft/vscode-edge-devtools#954]
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Windows 10
 - Extension version (*e.g.,* 1.2.3): 1.4.6

**Describe the bug:**

I get two notifications when starting VS Code:

- Microsoft Edge Tools server crashed 5 times in the last 3 minutes
- A request has failed. See the output for more information. Source: Microsoft Edge Tools for VS Code (extension)

**Repro steps:**

Upgraded to latest VS Code this week.

**Expected behavior:**

For the extension to work ;-) 

**Additional context:**

Output:

Error loading "hint" package from "c:\notOneDrive\source\british-council\Registrations\b2c.ui"
Trying to load shared version
Found hint at c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:139113 {
  status: 'AnalyzeError'
}
[Info  - 08:12:39] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\notOneDrive\source\british-council\Registrations\b2c.ui"
Trying to load shared version
Found hint at c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:139113 {
  status: 'AnalyzeError'
}
[Info  - 08:12:41] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\notOneDrive\source\british-council\Registrations\b2c.ui"
Trying to load shared version
Found hint at c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:139113 {
  status: 'AnalyzeError'
}
[Info  - 08:12:42] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\notOneDrive\source\british-council\Registrations\b2c.ui"
Trying to load shared version
Found hint at c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:139113 {
  status: 'AnalyzeError'
}
[Info  - 08:12:44] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\notOneDrive\source\british-council\Registrations\b2c.ui"
Trying to load shared version
Found hint at c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Connector local only works with local files or directories
    at Analyzer.analyze (c:\Users\colin_\AppData\Roaming\Code\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async c:\Users\colin_\.vscode\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.6\node_modules\vscode-webhint\dist\src\server.js:1:139113 {
  status: 'AnalyzeError'
}
[Error - 08:12:45] Connection to server got closed. Server will not be restarted.

**Comment by codepo8** [comment]
I had a similar issue and we're working on a fix, this should be ready soon. Sorry about that.

**Comment by lukkea** [comment]
@codepo8 
Looks like this is fixed?
Shall I close?

**Comment by antross** [comment]
@lukkea yes this was fixed with the 1.4.7 update. Thanks for the reminder!

**Comment by OpenWaygate** [comment]
I still have this problem with Microsoft Edge Tools for VS Code v1.4.7

Version: 1.67.0-insider (system setup)
Commit: a9288be67bab4e9c4dbe62207f01fafc2bdaadcb
Date: 2022-04-15T05:16:11.219Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22598

```
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:139192 {
  status: 'AnalyzeError'
}
[Info  - 10:16:40 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:139192 {
  status: 'AnalyzeError'
}
[Info  - 10:16:43 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:139192 {
  status: 'AnalyzeError'
}
[Info  - 10:16:47 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:139192 {
  status: 'AnalyzeError'
}
[Info  - 10:16:50 PM] Connection to server got closed. Server will restart.
Error loading "hint" package from "c:\Users\user_name\GitUp\chore\html"
Trying to load shared version
Found hint at c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\index.js
c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151
                throw new types_1.AnalyzerError(e, error_status_1.AnalyzerErrorStatus.AnalyzeError);
                      ^

AnalyzerError: Unable to parse axe results null
    at Analyzer.analyze (c:\Users\user_name\AppData\Roaming\Code - Insiders\User\globalStorage\ms-edgedevtools.vscode-edge-devtools\node_modules\hint\dist\src\lib\analyzer.js:151:23)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1214
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1139)
    at async t.Analyzer.validateTextDocument (c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:1519)
    at async c:\Users\user_name\.vscode-insiders\extensions\ms-edgedevtools.vscode-edge-devtools-1.4.7\node_modules\vscode-webhint\dist\src\server.js:1:139192 {
  status: 'AnalyzeError'
}
[Error - 10:16:54 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by antross** [comment]
@OpenWaygate thanks for the follow-up and for including the log. Looking at the log it appears this is a different root cause:

```
AnalyzerError: Unable to parse axe results null
```

I'll split this into a separate bug so we can track this particular cause independently, but it's definitely something we'll want to investigate.
